// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculeService.Data;

#nullable disable

namespace VehiculeService.Migrations
{
    [DbContext(typeof(VehiculeDbContext))]
    partial class VehiculeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehiculeService.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VitesseLimite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Vehicules", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Vehicule");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VehiculeService.Models.Camion", b =>
                {
                    b.HasBaseType("VehiculeService.Models.Vehicule");

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<int>("NbrEssieux")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Couleur = "Blanc",
                            Marque = "Volvo",
                            Matricule = "TU-1234",
                            Type = "Camion",
                            VitesseLimite = 90,
                            Capacite = 12000,
                            NbrEssieux = 3
                        });
                });

            modelBuilder.Entity("VehiculeService.Models.Voiture", b =>
                {
                    b.HasBaseType("VehiculeService.Models.Vehicule");

                    b.Property<int>("NbrPlaces")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Voiture");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Couleur = "Gris",
                            Marque = "Peugeot",
                            Matricule = "TU-5678",
                            Type = "Voiture",
                            VitesseLimite = 120,
                            NbrPlaces = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
