// <auto-generated />
using LivraisonService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivraisonService.Migrations
{
    [DbContext(typeof(LivraisonDbContext))]
    [Migration("20260514041443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LivraisonService.Models.AdresseLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ColisId")
                        .HasColumnType("int");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("AdressesLivraison", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "10 Rue de Marseille",
                            CodePostal = "1000",
                            ColisId = 1,
                            Ville = "Tunis"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "25 Avenue Habib Bourguiba",
                            CodePostal = "3000",
                            ColisId = 2,
                            Ville = "Sfax"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "8 Rue des Oliviers",
                            CodePostal = "4000",
                            ColisId = 3,
                            Ville = "Sousse"
                        });
                });

            modelBuilder.Entity("LivraisonService.Models.StatutLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatutsLivraison", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Libelle = "En attente"
                        },
                        new
                        {
                            Id = 2,
                            Libelle = "En cours"
                        },
                        new
                        {
                            Id = 3,
                            Libelle = "Livre"
                        },
                        new
                        {
                            Id = 4,
                            Libelle = "Annule"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
