// <auto-generated />
using System;
using ClientService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientService.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20260514050017_UserClientLinking")]
    partial class UserClientLinking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientService.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CompteId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CIN")
                        .IsUnique();

                    b.HasIndex("CompteId")
                        .IsUnique()
                        .HasFilter("[CompteId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "10 Rue de Marseille",
                            CIN = "CL001",
                            CodePostal = "1000",
                            Email = "amine.client@livraison.local",
                            Nom = "Ben Salah",
                            Prenom = "Amine",
                            Telephone = "71111111",
                            Ville = "Tunis"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "25 Avenue Habib Bourguiba",
                            CIN = "CL002",
                            CodePostal = "3000",
                            Email = "sarra.client@livraison.local",
                            Nom = "Trabelsi",
                            Prenom = "Sarra",
                            Telephone = "72222222",
                            Ville = "Sfax"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "8 Rue des Oliviers",
                            CIN = "CL003",
                            CodePostal = "4000",
                            Email = "youssef.client@livraison.local",
                            Nom = "Jaziri",
                            Prenom = "Youssef",
                            Telephone = "73333333",
                            Ville = "Sousse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
