// <auto-generated />
using LivreurService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivreurService.Migrations
{
    [DbContext(typeof(LivreurDbContext))]
    [Migration("20260514041443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LivreurService.Models.Livreur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RaisonSocial")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CIN")
                        .IsUnique();

                    b.ToTable("Livreurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CIN = "12345678",
                            CodePostal = "1000",
                            RaisonSocial = "Express Nord",
                            Ville = "Tunis"
                        },
                        new
                        {
                            Id = 2,
                            CIN = "87654321",
                            CodePostal = "3000",
                            RaisonSocial = "Rapid Sud",
                            Ville = "Sfax"
                        },
                        new
                        {
                            Id = 3,
                            CIN = "11223344",
                            CodePostal = "4000",
                            RaisonSocial = "Livraison Centre",
                            Ville = "Sousse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
