// <auto-generated />
using System;
using ColisService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColisService.Migrations
{
    [DbContext(typeof(ColisDbContext))]
    [Migration("20260514041443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColisService.Models.Colis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLivraison")
                        .HasColumnType("datetime2");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("LivreurId")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Poids")
                        .HasColumnType("float");

                    b.Property<int>("StatutLivraisonId")
                        .HasColumnType("int");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Colis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DateLivraison = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Ordinateur portable",
                            LivreurId = 1,
                            Montant = 2200m,
                            Poids = 2.5,
                            StatutLivraisonId = 3,
                            Volume = 0.01
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            DateLivraison = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Documents administratifs",
                            LivreurId = 2,
                            Montant = 35m,
                            Poids = 0.20000000000000001,
                            StatutLivraisonId = 1,
                            Volume = 0.002
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            DateLivraison = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Pieces auto",
                            LivreurId = 3,
                            Montant = 780m,
                            Poids = 12.300000000000001,
                            StatutLivraisonId = 2,
                            Volume = 0.14999999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
